server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: add
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
dubbo:
  application:
    name: dubbo-api-platform-backend-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

